### ISSUE TITLE
Category missing, how to add it?

### ISSUE THREAD

**Issue by Buda9** [MoodleNRW/moodle-mod_gameofknowledge#10]
Hi there and thank you for this plugin.

I was trying to test it, however, I couldn't finish adding an activity. It's asking me to choose a category, but I don't see a way to add categories. Could you please help me?

![Screenshot_205](https://github.com/MoodleNRW/moodle-mod_gameofknowledge/assets/1422662/67986359-e66b-4229-b317-1af8db37aae5)

Thank you

Ps Moodle 4.3

**Comment by larsbonczek** [comment]
Hi there, sorry for the (very) late response!

You need to select a question category in this field from which the questions are randomly drawn during the game. You can create question categories in the course's question bank:
https://docs.moodle.org/403/en/Question_categories

However, please be aware that this plugin was created during a Hackathon and is not actively maintained.
